evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }


_afficher_events:
    path:     /afficherevent
    defaults: { _controller: EvenementBundle:Default:afficher }

_ajouter_events:
    path:     /ajouterevent
    defaults: { _controller: EvenementBundle:Default:ajout }

_supprimer_events:
    path:     /supprimerevent
    defaults: { _controller: EvenementBundle:Default:supprimer }

_modifier_events:
    path:     /modifierevent
    defaults: { _controller: EvenementBundle:Default:modifier }


_rechercher_events_club:
    path:     /recherchereventclub
    defaults: { _controller: EvenementBundle:Default:rechercheClub }

_rechercher_events_date:
    path:     /recherchereventdate
    defaults: { _controller: EvenementBundle:Default:rechercheDate }
_rechercher_events_nom:
    path:     /recherchereventnom
    defaults: { _controller: EvenementBundle:Default:rechercheNom }
_traiter_prop_events:
    path:     /traiterpropevent
    defaults: { _controller: EvenementBundle:Default:traiterPropositionsEvt }
_accepter_prop_events:
    path:     /accepterprop
    defaults: { _controller: EvenementBundle:Default:accepterPropositionsEvt }
_refuser_prop_events:
    path:     /refuserprop
    defaults: { _controller: EvenementBundle:Default:refuserPropositionsEvt }
_participer_events:
    path:     /participerevent
    defaults: { _controller: EvenementBundle:Default:participerEvent }
_afficher_tri_events:
    path:     /affichertrievent
    defaults: { _controller: EvenementBundle:Default:afficherTri }